### ISSUE TITLE
Files which aren't mentioned get added to the archive

### ISSUE THREAD

**Issue by sigmaboy** [BubblesInTheTub/torrent7z#1]
I found a bug when creating the archives.

Files get added even if they aren't mentioned.
steps to reproduce

```bash
mkdir test
dd if=/dev/urandom of=./here.blob bs=1M count=2
cp here.blob test/here.blob
t7z a here.blob
```
The resulted file here.blob.7z also includes the file from the test directory
```bash
t7z l here.blob.7z
```
```bash
torrent7z_0.9.2beta/
using 7-Zip (A) 4.65  Copyright (c) 1999-2009 Igor Pavlov  2009-02-03

/tmp/t7z_14143.tmp                    .....      2097152      2126028  here.blob
                    .....      2097152               test/here.blob
```

**Comment by BubblesInTheTub** [comment]
This is one of those "it's a feature, not a bug" moments. The original t7z tool had this behaviour where it searches for the file name within the sub-directories as well.

I'll modify the tool so that it doesn't do this by default and then add a key to explicitly enable this behaviour.

**Comment by BubblesInTheTub** [comment]
I've updated the code and generated binaries with the fix. The default behavior has been changed to resolve this issue. It can be re-enabled with the new (-rs) switch.

It was tested at my end, but please also do check. I'll close this issue after your confirmation.

Thanks for testing and reporting this!

**Comment by sigmaboy** [comment]
Works like a charm. Can be closed
