### ISSUE TITLE
Use github releases instead of a directory containing binaries

### ISSUE THREAD

**Issue by sigmaboy** [BubblesInTheTub/torrent7z#4]
Github has a good feature for creating releases. 

Just simply tag the commit you want to have for a new release/version.
Then craft a github release from the tag via web.
You can upload whatever files you want to that release. for example windows and linux binaries.

https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by BubblesInTheTub** [comment]
Thanks, Sigmaboy. I'll check his out.

**Comment by BubblesInTheTub** [comment]
The latest binaries have been released using this approach. I wasn't aware of this option till you brought it up.

**Comment by sigmaboy** [comment]
@BubblesInTheTub But I mentioned that removing binaries from the actual git project should be done. You can even tag old commits and also release old versions retrospectively and upload the binaries there.

My goal was to remove every binary from the git project and publish them via release instead.
