### ISSUE TITLE
directory won't get added when mentioning unless -rs is used

### ISSUE THREAD

**Issue by sigmaboy** [BubblesInTheTub/torrent7z#5]
p7zip supports adding directories when mentioning via command line.

torrent7z doesn't do this anymore after the "searching for the file in all subdirectories" change.

I expect torrent7z to work mostly identical to p7zip.
### Preparation:
```bash
mkdir test
touch test/my.file
```
### p7zip's 7za command line program:
```bash
7za a test.7z test
```
The created archive contains a directory test with the file _my.file_

### torrent7z behaviour
```bash
t7z a test.7z test
```
torrent7z only displays an error:
```
error: no files match: test
error: no files to process
```

_-rs_ parameter works as a workaround for this issue. 
In general a behaviour like 7za for the most scenarios would be awesome.

Thank you in advance

**Comment by sigmaboy** [comment]
I found out that the _file_exists_ function doesn't work as expect.
https://github.com/BubblesInTheTub/torrent7z/blob/116923447a21cb3573b4449e26bb52d7134e2471/linux_src/p7zip_4.65/torrent7z/t7z.cpp#L756

Inside the function _process_mask_ returns zero (don't really know what does that) so it won't get into the point where it determines if it's a directory or a file (```EAX=fi.fileInfo.IsDir()?2:1;```), beside that the isDir function returns that it's a file, not a directory.

I could write something using ```#include <sys/stat.h>``` to reimplement _file_exists_
Is this okay or do you have a smarter solution? (as my C/C++ skills are just mediocre).

**Comment by BubblesInTheTub** [comment]
Heya, just saw the issue now.   It's good that you're testing the tool exhaustively. A minor tweak should fix it. I'll look into it.

As for reimplementing file_exists using the sys/stat.h. I think it is a POSIX only library, we'd have to make an equivalent function that works for Windows as well. What do we gain from the re-implentation?

**Comment by sigmaboy** [comment]
do you plan to merge the source code trees, as for the moment they are derivated?
If yes a posix only function makes no sense. it was only a idea.
I could search for a windows  + posix solution. Or maybe just have a better understanding of the data type "NWindows::NFile::NFind::CFileInfo" which is used to check the file type.

**Comment by BubblesInTheTub** [comment]
Yes, I plan on eventually using classes to abstract away the platform specific variations. 
So, about the issue at hand. I've updated the code to resolve the issue. Could you try it out, please?

Thank again for continuing to test the tool! :)

**Comment by sigmaboy** [comment]
in general it works now but now it had an unexpected behaviour.

The 7z archive gets written into the mentioned directory, when the archive name is ommited and a trailing slash is added to the archive. I expected that it gets written into the current working directory. 

example:
```bash
mkdir test
touch test/my.file
t7z a test/
```
Output:
```bash
[...]
Creating archive test//file.7z.tmp
[...]
```

The resulting archive is in the subdirectory instead of the current directory.
```bash
find ./
```

Output:
```bash
./
./test
./test/file
./test/file.7z
```

Everything works as expect if the trailing "/" is missing. Also when the archive is mentioned as the first argument after the "a".

Working:
```bash
t7z a archive.7z test
t7z a archive.7z test/
t7z a test
```

So I think (if not mentioned otherwise) the archive should always be written into the current working directory.

Thank you very much for your help and maintainership. It's awesome!

**Comment by sigmaboy** [comment]
@BubblesInTheTub any news regarding this issue

**Comment by BubblesInTheTub** [comment]
@sigmaboy, sorry I was a bit inactive due to work/family pressure. I have an idea to fix this, will try to close it this weekend.

**Comment by BubblesInTheTub** [comment]
I looked into this, there was another related issue. When you try to create an archive of a directory without specifying the name, the resulting auto generated name would be of a file inside it rather than based on the directory name itself.

A fix has been applied and was tested in a limited fashion. Could you try out the latest binaries and confirm, please?

**Comment by sigmaboy** [comment]
As far as my testing went I can verify that it now works as expected. This is awesome. Imo in can be closed!
